[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "corepack enable && pnpm install --frozen-lockfile && pnpm --filter fibranexus-server run build"
]

[start]
cmd = "pnpm --filter fibranexus-server start"
